[package]
name = "serge-core"
version = "0.1.0"
authors = ["Michael Pfeifer <michael.k.pfeifer@googlemail.com>"]
edition = "2021"
license-file = "LICENCE"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
